var ForeColorsArray = new Array
("darkgray",
"darkred",
"rosybrown",
"mediumvioletred",
"hotpink",
"red",
"orange",
"goldenrod",
"seagreen",
"cadetblue",
"lightseagreen",
"mediumseagreen",
"darkseagreen",
"limegreen",
"mediumturquoise",
"deepskyblue",
"blue",
"mediumblue",
"steelblue",
"darkviolet",
"mediumorchid",
"orchid",
"plum",
"magenta");
var ForeColorDefault = ForeColorsArray[8];
