var TextNerdBanPrefixStr         = 'Вы нарушаете правила чата.\nНастоятельно рекомендуем придерживаться правил\nПредупреждение/напоминание ';
var TextExitConfirmStr           = 'Покинуть чат?';
var TextInputTooLongStr          = 'Превышена максимальная длина строки ввода';
var TextInputTooMayImgPrefixStr  = 'Вы не можете отправить более ';
var TextInputTooMayImgPostfixStr = ' картинок в одном сообщении';
var TextInputMessEmptyStr        = 'Вы пытаетесь отправить пустое сообщение';
var TextInputMessSelfStr         = 'Вы пытаетесь отправить сообщение самому себе ;)';
var TextInputMessNoPvtToNickSt   = 'Вы пытаетесь отправить приватное сообщение не указав получателя ;)';
var TextInputMessAllDuplicateStr = 'Вы пытаетесь послать всем два одинаковых сообщения подряд. Смысл?';
var TextInputMaxSpeedPrefixStr   = 'Максимальная скорость отправки сообщений в чате:';
TextInputMaxSpeedPrefixStr  += '\n';
var TextInputMaxSpeedItemsInStr  = ' сообщений в течении ';
var TextInputMaxSpeedPostfixStr  = ' секунд.';
TextInputMaxSpeedPostfixStr += '\n';
TextInputMaxSpeedPostfixStr += 'Ваша скорость набора превышает этот порог';
TextInputMaxSpeedPostfixStr += '\n';
TextInputMaxSpeedPostfixStr += 'ПОДОЖДИТЕ НЕСКОЛЬКО СЕКУНД.';
TextInputMaxSpeedPostfixStr += '\n';
TextInputMaxSpeedPostfixStr += 'СПАСИБО!';
var TextPrivateTitlePrefixStr    = 'Окно для приватных (личных) сообщений для ';
var TextPrivateTitlePostfixStr   = '';
var TextNickMuteFromTitlePrefixStr  = 'Отключить ОБЩИЕ сообщения ОТ \"';
var TextNickMuteFromTitlePostfixStr = '\"';
var TextNickMPvtFromTitlePrefixStr  = 'Отключить ПРИВАТНЫЕ сообщения ОТ \"';
var TextNickMPvtFromTitlePostfixStr = '\"';
var TextNickMuteToTitlePrefixStr    = 'Отключить сообщения ДЛЯ \"';
var TextNickMuteToTitlePostfixStr   = '\"';
var TextNickItemTitlePrefixStr      = 'Щелчок - выбор \"';
var TextNickItemTitlePostfixStr     = '\" адресатом';
var TextNickInfoTitlePrefixStr      = 'По нику есть информация. Щелчок - справка о нике \"';
var TextNickInfoTitlePostfixStr     = '\"';
var TextNickNoteTitlePrefixStr      = 'По данному нику есть ваша заметка. Щелчок - справка о нике \"';
var TextNickNoteTitlePostfixStr     = '\"';
var TextNickHashErrorAlertPrefixStr = 'Ошибка хеша ников:';
var TextNickPanelHeaderPrefixStr    = '<div align=center><nobr><b>Перечень ников</b>.(';
var TextNickPanelHeaderPostfixStr   = ')<wbr></div>';
var TextNickPanelMuteFromHeadStr    = 'X0';
var TextNickPanelMPvtFromHeadStr    = 'x0';
var TextNickPanelMuteToHeadStr      = '0x';
var TextNickPanelGenderHeadStr      = '&nbsp;';
var TextNickPanelNickNameHeadStr    = '<u>Ник</u>';
var TextNickSysInfoHeadStr          = 'Ваше подключение:';
var TextNickTotalGMalesStr          = 'Парней';
var TextNickTotalGFemalesStr        = 'Девушек';
var TextNickTotalGUndefinedStr      = 'Прочих';
var TextNickTotalAllStr             = '<b>ВСЕГО</b>';
var TextSmileItemTitleStr           = 'Шелкните на картинке для вставки ее в сообщение';
var TextSmilesPanelHeaderStr        = '<div align=center><nobr><b>Панель смайлов</b><wbr></div><wbr>';
var TextSmilesPanelMainSubHeaderStr = '<div align=left><nobr>Основные смайлы<wbr></div><wbr>';
var TextSmilesPanelAdd1SubHeaderStr = '<div align=left><nobr>Смайлы с www.phpbb.com<wbr></div><wbr>';
var TextSmilesPanelAdd2SubHeaderStr = '<div align=left><nobr>Смайлы с smiliki.by.ru<wbr></div><wbr>';
var TextSmilesPanelAdd3SubHeaderStr = '<div align=left><nobr>Смайлы найденые чатланами<wbr></div><wbr>';
var TextSetupPanelHeaderStr         = '<div align=center><nobr><b>Мои настройки</b><wbr></div><wbr>';
var TextSetupPanelBackColorSignStr  = 'Цвет фона';
var TextSetupPanelSoundOnPrivateTitleStr = 'Выдавать звуковое сообщение при приеме нового приватного сообщения';
var TextSetupPanelSoundOnPrivateSignStr  = 'Звук при приеме привата';
var TextSetupPanelSoundOnNewUserTitleStr = 'Выдавать звуковое сообщение при входе в чат нового ника';
var TextSetupPanelSoundOnNewUserSignStr  = 'Звук при входе нового ника';
var TextSetupPanelSoundOnMyMessTitleStr  = 'Выдавать звуковое сообщение при приеме \"обычного\" сообщения адресованного вам';
var TextSetupPanelSoundOnMyMessSignStr   = 'Звук при сообщении для меня';
var TextSetupPanelKeepPrivateTitleStr    = 'Не сбрасывать флаг \"Приватно\" после отправки сообщения';
var TextSetupPanelKeepPrivateSignStr     = 'Сохранять \"Приватно\"';
var TextSetupPanelKeepMessToTitleStr     = 'Не очищать поле \"Ник-Адресат\" после отправки сообщения';
var TextSetupPanelKeepMessToSignStr      = 'Сохранять адресата';
var TextSetupPanelGZIPStreamTitleStr     = 'Использовать сжатие данных \"GZIP Stream\", если поддерживается броузером';
var TextSetupPanelGZIPStreamSignStr      = 'Сжатие данных';
var TextSetupPanelDoNotScrollTitleStr    = 'Не передвигать полосу прокрутки в окне сообщения при получении новых сообщений';
var TextSetupPanelDoNotScrollSignStr     = 'Запретить автоскроллинг';
var TextSetupPanelCarbonCopy2PvtTitleStr = 'Копировать общие сообщения написаные вами и адресованые вам в окно привата (наклонным шрифтом)';
var TextSetupPanelCarbonCopy2PvtSignStr  = 'Расширеный <i>приват</i>';
var TextSetupPanelClearPvtButtonTitleStr = 'Очисть окно привата';
var TextSetupPanelClearPvtButtonTextStr  = 'Очистить приват';
var TextMyInfoPanelHeaderStr             = '<div align=center>Загрузка информации о ВАС</div>';
var TextNickInfoPanelHeaderPrefixStr     = '<div align=center>Загрузка данных: ';
var TextNickInfoPanelHeaderPostfixStr    = '</div>';
var TextForumPanelHeaderStr              = '<div align=center>Загрузка данных с форума</div>';
var TextNickInfoPanelHeaderPrefixStr     = '<div align=center>Загрузка данных: ';
var TextNickInfoPanelHeaderPostfixStr    = '</div>';
var TextNickAnchorTitlePrefixStr         = 'Щелчок - выбор \"';
var TextNickAnchorTitlePostfixStr        = '\" адресатом';
var TextNickNotesInfoTitlePrefixStr      = 'По нику есть информация. Щелчок - справка о нике \"';
var TextNickNotesInfoTitlePostfixStr     = '\"';
var TextNickNotesNotesTitlePrefixStr     = 'По данному нику есть ваша заметка. Щелчок - справка о нике \"';
var TextNickNotesNotesTitlePostfixStr    = '\"';
var TextNickHeadInfoTitleStr             = 'По нику есть информация. Щелчок - быстрый переход';
var TextNickHeadNotesTitleStr            = 'По данному нику есть ваша заметка. Щелчок - быстрый переход';
