<!-- Chat Banner Network -->
<script language="javascript" type="text/javascript"><!--
bn_url='/chatadvt/usr/usrlocal/text/chatclnt_advt_zz_body.htm';
bn_rnd=Math.round((Math.random()*10000000));
document.write('<iframe src="'+bn_url+'?bn_rnd='+bn_rnd+'" width=568 height=60 frameborder=0 vspace=0 hspace=0 marginwidth=0 marginheight=0 id="ChatVinAdvt_'+bn_rnd+'" name="ChatVinAdvtFrame_'+bn_rnd+'" scrolling=no></iframe>');
//--></script>
<!-- /Chat Banner Network -->
